using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

// General Information about an assembly is controlled through the following 
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
[assembly: AssemblyTitle("BlazorWebFormsComponents.Snippets")]
[assembly: AssemblyDescription("Code snippets for BlazorWebFormsComponents library")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Jeffrey T. Fritz")]
[assembly: AssemblyProduct("BlazorWebFormsComponents.Snippets")]
[assembly: AssemblyCopyright("Copyright © Jeffrey T. Fritz 2019-2026")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

// Setting ComVisible to false makes the types in this assembly not visible 
// to COM components.  If you need to access a type in this assembly from 
// COM, set the ComVisible attribute to true on that type.
[assembly: ComVisible(false)]

// Version information is auto-generated by Nerdbank.GitVersioning

