// =============================================================================
// Global using directives for Web Forms → Blazor migration.
//
// Type aliases (Page, MasterPage, ImageClickEventArgs) and BWFC namespaces are
// provided automatically by the BlazorWebFormsComponents .targets file.
// This file adds Blazor infrastructure usings for code-behind files.
//
// Generated by webforms-to-blazor — Layer 1 scaffold
// =============================================================================

// Blazor component infrastructure — provides [Inject], [Parameter],
// [SupplyParameterFromQuery], NavigationManager, ComponentBase, etc.
global using Microsoft.AspNetCore.Components;
global using Microsoft.AspNetCore.Components.Web;
global using Microsoft.AspNetCore.Components.Routing;

// Identity infrastructure
global using Microsoft.AspNetCore.Components.Authorization;
global using Microsoft.AspNetCore.Identity;
global using BlazorWebFormsComponents;
global using BlazorWebFormsComponents.Enums;
global using BlazorWebFormsComponents.LoginControls;
global using BlazorWebFormsComponents.Validations;
