// =============================================================================
// Identity compatibility shims for Blazor migration.
//
// These shims bridge ASP.NET Web Forms membership/identity patterns to
// ASP.NET Core Identity equivalents.
//
// Generated by webforms-to-blazor — Layer 1 scaffold
// =============================================================================

// TODO(bwfc-identity): Configure ASP.NET Core Identity to replace Web Forms Membership
// The following patterns need manual migration:
//   Membership.GetUser()          → UserManager<IdentityUser>.GetUserAsync()
//   Membership.ValidateUser()     → SignInManager<IdentityUser>.PasswordSignInAsync()
//   FormsAuthentication.SignOut()  → SignInManager<IdentityUser>.SignOutAsync()
//   Roles.IsUserInRole()          → UserManager<IdentityUser>.IsInRoleAsync()
//
// See: https://learn.microsoft.com/aspnet/core/security/authentication/identity

using Microsoft.AspNetCore.Identity;
