using SharedSampleObjects.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace BeforeWebForms.ControlSamples.GridView
{
	public partial class AutoGeneratedColumns : System.Web.UI.Page
	{
		protected void Page_Load(object sender, EventArgs e)
		{

		}

		public List<Customer> GetCustomers()
		{
			return Customer.GetCustomers(5, 0, "foo", out _).ToList();
		}
	}
}
