<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="BeforeWebForms.ControlSamples.GridView.Default" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">

  <h2>GridView control homepage</h2>

  <div>
      <a href="Default.aspx">Default</a> | <a href="AutoGeneratedColumns.aspx">AutoGeneratedColumns </a> | <a href="TemplateFields.aspx">Template Fields</a>
  </div>

  <p>This is just a simple example of a GridView with a selectMethod</p>

  <asp:gridview id="CustomersGridView" 
    autogeneratecolumns="False"
    emptydatatext="No data available."
    selectMethod="GetCustomers"
    ItemType="SharedSampleObjects.Models.Customer"
    runat="server" DataKeyNames="CustomerID">
      <Columns>
          <asp:BoundField DataField="CustomerID" HeaderText="CustomerID" 
              InsertVisible="False" ReadOnly="True" SortExpression="CustomerID" />
          <asp:BoundField DataField="CompanyName" HeaderText="CompanyName" 
              SortExpression="CompanyName" />
          <asp:BoundField DataField="FirstName" HeaderText="FirstName" 
              SortExpression="FirstName" />
          <asp:BoundField DataField="LastName" HeaderText="LastName" 
              SortExpression="LastName" />
        <asp:TemplateField>
			        <ItemTemplate>
				        <button type="button">Click Me! <%#:Item.FirstName %></button>
			         </ItemTemplate>
		    </asp:TemplateField>
        <asp:HyperLinkField
          DataTextFormatString="Search for {0}" DataTextField="CompanyName"
          DataNavigateUrlFields="CompanyName, FirstName, LastName" DataNavigateUrlFormatString="https://www.bing.com/search?q={0} {1} {2}" />
        <asp:CheckBoxField
          DataField="Active"
          HeaderText="Checkboxes"
          ReadOnly="false"
          Text="This is a checkbox field" />

      </Columns>
  </asp:gridview>
</asp:Content>
