// =============================================================================
// Web Forms compatibility shims for Blazor migration.
//
// These shims bridge common Web Forms types and patterns to their Blazor/BWFC
// equivalents. The BWFC NuGet package provides most type aliases automatically
// via its .targets file (Page, MasterPage, ImageClickEventArgs).
//
// This file adds project-level shims for patterns not covered by the package.
//
// DI registration: AddBlazorWebFormsComponents() in Program.cs registers:
//   - SessionShim     (scoped) — drop-in for Session["key"] access
//   - CacheShim       (scoped) — drop-in for Cache["key"] access
//   - ServerShim      (scoped) — drop-in for Server.MapPath() etc.
//   - ConfigurationManager — shim for AppSettings["key"] access
//
// Code-behind files with Session["key"] or Cache["key"] get auto-wired
// [Inject] properties during L1 migration (SessionDetectTransform).
//
// Generated by webforms-to-blazor — Layer 1 scaffold
// =============================================================================

// ConfigurationManager shim — allows Web Forms configuration access patterns
// to work against ASP.NET Core's IConfiguration.
// Usage: ConfigurationManager.AppSettings["key"] maps to IConfiguration["key"]
using BlazorWebFormsComponents;
