namespace BlazorWebFormsComponents.Enums;

/// <summary>
/// Specifies a hatch pattern style for chart backgrounds. Matches the ASP.NET Web Forms
/// ChartHatchStyle enum, which mirrors the GDI+ HatchStyle values.
/// </summary>
public enum ChartHatchStyle
{
	None = 0,
	BackwardDiagonal = 1,
	Cross = 2,
	DarkDownwardDiagonal = 3,
	DarkHorizontal = 4,
	DarkUpwardDiagonal = 5,
	DarkVertical = 6,
	DashedDownwardDiagonal = 7,
	DashedHorizontal = 8,
	DashedUpwardDiagonal = 9,
	DashedVertical = 10,
	DiagonalBrick = 11,
	DiagonalCross = 12,
	Divot = 13,
	DottedDiamond = 14,
	DottedGrid = 15,
	ForwardDiagonal = 16,
	Horizontal = 17,
	HorizontalBrick = 18,
	LargeCheckerBoard = 19,
	LargeConfetti = 20,
	LargeGrid = 21,
	LightDownwardDiagonal = 22,
	LightHorizontal = 23,
	LightUpwardDiagonal = 24,
	LightVertical = 25,
	NarrowHorizontal = 26,
	NarrowVertical = 27,
	OutlinedDiamond = 28,
	Percent05 = 29,
	Percent10 = 30,
	Percent20 = 31,
	Percent25 = 32,
	Percent30 = 33,
	Percent40 = 34,
	Percent50 = 35,
	Percent60 = 36,
	Percent70 = 37,
	Percent75 = 38,
	Percent80 = 39,
	Percent90 = 40,
	Plaid = 41,
	Shingle = 42,
	SmallCheckerBoard = 43,
	SmallConfetti = 44,
	SmallGrid = 45,
	SolidDiamond = 46,
	Sphere = 47,
	Trellis = 48,
	Vertical = 49,
	Wave = 50,
	Weave = 51,
	WideDownwardDiagonal = 52,
	WideUpwardDiagonal = 53,
	ZigZag = 54
}
