using BlazorWebFormsComponents.DataBinding;
using BlazorWebFormsComponents.Enums;
using BlazorWebFormsComponents.Interfaces;
using Microsoft.AspNetCore.Components;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;

namespace BlazorWebFormsComponents
{
	/// <summary>
	/// Blazor component emulating the ASP.NET Web Forms DetailsView control.
	/// Displays a single record from a data source in a table layout with one row per field.
	/// </summary>
	/// <typeparam name="ItemType">The type of the data items.</typeparam>
	public partial class DetailsView<ItemType> : DataBoundComponent<ItemType>, IDetailsViewStyleContainer, IPagerSettingsContainer
	{
		#region Properties

		/// <summary>
		/// Gets or sets whether to automatically generate rows for each field in the data source.
		/// </summary>
		[Parameter]
		public bool AutoGenerateRows { get; set; } = true;

		/// <summary>
		/// Gets or sets the names of the primary key fields for the data source.
		/// </summary>
		[Parameter]
		public string DataKeyNames { get; set; }

		/// <summary>
		/// Gets or sets the default mode of the DetailsView control.
		/// </summary>
		[Parameter]
		public DetailsViewMode DefaultMode { get; set; } = DetailsViewMode.ReadOnly;

		/// <summary>
		/// Gets or sets whether paging is enabled.
		/// </summary>
		[Parameter]
		public bool AllowPaging { get; set; }

		/// <summary>
		/// Gets or sets whether to display an Edit button in the command row.
		/// </summary>
		[Parameter]
		public bool AutoGenerateEditButton { get; set; }

		/// <summary>
		/// Gets or sets whether to display a Delete button in the command row.
		/// </summary>
		[Parameter]
		public bool AutoGenerateDeleteButton { get; set; }

		/// <summary>
		/// Gets or sets whether to display an Insert button in the command row.
		/// </summary>
		[Parameter]
		public bool AutoGenerateInsertButton { get; set; }

		/// <summary>
		/// Gets or sets the gridlines style for the table.
		/// </summary>
		[Parameter]
		public GridLines GridLines { get; set; } = GridLines.Both;

		/// <summary>
		/// Gets or sets the cell padding for the table.
		/// </summary>
		[Parameter]
		public int CellPadding { get; set; } = -1;

		/// <summary>
		/// Gets or sets the cell spacing for the table.
		/// </summary>
		[Parameter]
		public int CellSpacing { get; set; } = 0;

		/// <summary>
		/// Gets or sets the header text for the DetailsView control.
		/// </summary>
		[Parameter]
		public string HeaderText { get; set; }

		/// <summary>
		/// Gets or sets the footer text for the DetailsView control.
		/// </summary>
		[Parameter]
		public string FooterText { get; set; }

		/// <summary>
		/// Gets or sets the text to display when the data source is empty.
		/// </summary>
		[Parameter]
		public string EmptyDataText { get; set; }

		/// <summary>
		/// Gets or sets the current page index (zero-based).
		/// </summary>
		[Parameter]
		public int PageIndex { get; set; }

		/// <summary>
		/// Gets or sets the caption text rendered in a caption element at the top of the table.
		/// </summary>
		[Parameter]
		public string Caption { get; set; }

		/// <summary>
		/// Gets or sets the horizontal or vertical position of the caption element.
		/// </summary>
		[Parameter]
		public TableCaptionAlign CaptionAlign { get; set; } = TableCaptionAlign.NotSet;

		/// <summary>
		/// Gets the total number of pages (one item per page in DetailsView).
		/// </summary>
		public int PageCount => Items != null ? Items.Count() : 0;

		/// <summary>
		/// Gets the current display mode of the DetailsView control.
		/// </summary>
		public DetailsViewMode CurrentMode { get; private set; }

		/// <summary>
		/// Gets the currently displayed item.
		/// </summary>
		public ItemType CurrentItem { get; private set; }

		#endregion

		#region TableItemStyle Properties (IDetailsViewStyleContainer)

		/// <summary>
		/// Gets or sets the style applied to data rows.
		/// </summary>
		public TableItemStyle RowStyle { get; internal set; } = new TableItemStyle();

		/// <summary>
		/// Gets or sets the style applied to alternating data rows.
		/// </summary>
		public TableItemStyle AlternatingRowStyle { get; internal set; } = new TableItemStyle();

		/// <summary>
		/// Gets or sets the style applied to the header row.
		/// </summary>
		public TableItemStyle HeaderStyle { get; internal set; } = new TableItemStyle();

		/// <summary>
		/// Gets or sets the style applied to the footer row.
		/// </summary>
		public TableItemStyle FooterStyle { get; internal set; } = new TableItemStyle();

		/// <summary>
		/// Gets or sets the style applied to the command row.
		/// </summary>
		public TableItemStyle CommandRowStyle { get; internal set; } = new TableItemStyle();

		/// <summary>
		/// Gets or sets the style applied to the row being edited.
		/// </summary>
		public TableItemStyle EditRowStyle { get; internal set; } = new TableItemStyle();

		/// <summary>
		/// Gets or sets the style applied to the row in insert mode.
		/// </summary>
		public TableItemStyle InsertRowStyle { get; internal set; } = new TableItemStyle();

		/// <summary>
		/// Gets or sets the style applied to field header cells.
		/// </summary>
		public TableItemStyle FieldHeaderStyle { get; internal set; } = new TableItemStyle();

		/// <summary>
		/// Gets or sets the style applied to the empty data row.
		/// </summary>
		public TableItemStyle EmptyDataRowStyle { get; internal set; } = new TableItemStyle();

		/// <summary>
		/// Gets or sets the style applied to the pager row.
		/// </summary>
		public TableItemStyle PagerStyle { get; internal set; } = new TableItemStyle();

		#endregion

		#region Style RenderFragment Parameters

		[Parameter] public RenderFragment RowStyleContent { get; set; }
		[Parameter] public RenderFragment AlternatingRowStyleContent { get; set; }
		[Parameter] public RenderFragment HeaderStyleContent { get; set; }
		[Parameter] public RenderFragment FooterStyleContent { get; set; }
		[Parameter] public RenderFragment CommandRowStyleContent { get; set; }
		[Parameter] public RenderFragment EditRowStyleContent { get; set; }
		[Parameter] public RenderFragment InsertRowStyleContent { get; set; }
		[Parameter] public RenderFragment FieldHeaderStyleContent { get; set; }
		[Parameter] public RenderFragment EmptyDataRowStyleContent { get; set; }
		[Parameter] public RenderFragment PagerStyleContent { get; set; }

		#endregion

		#region PagerSettings

		/// <summary>
		/// Gets the pager settings for the DetailsView.
		/// </summary>
		public PagerSettings PagerSettings { get; internal set; } = new PagerSettings();

		/// <summary>
		/// Content for the PagerSettings sub-component.
		/// </summary>
		[Parameter] public RenderFragment PagerSettingsContent { get; set; }

		#endregion

		#region Templates

		/// <summary>
		/// Gets or sets the header template.
		/// </summary>
		[Parameter]
		public RenderFragment HeaderTemplate { get; set; }

		/// <summary>
		/// Gets or sets the footer template.
		/// </summary>
		[Parameter]
		public RenderFragment FooterTemplate { get; set; }

		/// <summary>
		/// Gets or sets the template to display when the data source is empty.
		/// </summary>
		[Parameter]
		public RenderFragment EmptyDataTemplate { get; set; }

		/// <summary>
		/// Gets or sets the pager template.
		/// </summary>
		[Parameter]
		public RenderFragment PagerTemplate { get; set; }

		/// <summary>
		/// Gets or sets the field definitions for the DetailsView.
		/// </summary>
		[Parameter]
		public RenderFragment Fields { get; set; }

		/// <summary>
		/// Gets or sets the child content (alias for Fields).
		/// </summary>
		[Parameter]
		public RenderFragment ChildContent { get; set; }

		#endregion

		#region Events

		/// <summary>
		/// Occurs when a button within the control is clicked.
		/// </summary>
		[Parameter]
		public EventCallback<DetailsViewCommandEventArgs> ItemCommand { get; set; }

		/// <summary>
		/// Occurs before a delete operation.
		/// </summary>
		[Parameter]
		public EventCallback<DetailsViewDeleteEventArgs> ItemDeleting { get; set; }

		/// <summary>
		/// Occurs after a delete operation.
		/// </summary>
		[Parameter]
		public EventCallback<DetailsViewDeletedEventArgs> ItemDeleted { get; set; }

		/// <summary>
		/// Occurs before an insert operation.
		/// </summary>
		[Parameter]
		public EventCallback<DetailsViewInsertEventArgs> ItemInserting { get; set; }

		/// <summary>
		/// Occurs after an insert operation.
		/// </summary>
		[Parameter]
		public EventCallback<DetailsViewInsertedEventArgs> ItemInserted { get; set; }

		/// <summary>
		/// Occurs before an update operation.
		/// </summary>
		[Parameter]
		public EventCallback<DetailsViewUpdateEventArgs> ItemUpdating { get; set; }

		/// <summary>
		/// Occurs after an update operation.
		/// </summary>
		[Parameter]
		public EventCallback<DetailsViewUpdatedEventArgs> ItemUpdated { get; set; }

		/// <summary>
		/// Occurs when the mode of the control is changing.
		/// </summary>
		[Parameter]
		public EventCallback<DetailsViewModeEventArgs> ModeChanging { get; set; }

		/// <summary>
		/// Occurs after the mode of the control has changed.
		/// </summary>
		[Parameter]
		public EventCallback<DetailsViewModeEventArgs> ModeChanged { get; set; }

		/// <summary>
		/// Occurs when the page index is changing.
		/// </summary>
		[Parameter]
		public EventCallback<PageChangedEventArgs> PageIndexChanging { get; set; }

		/// <summary>
		/// Occurs after the page index has changed.
		/// </summary>
		[Parameter]
		public EventCallback<PageChangedEventArgs> PageIndexChanged { get; set; }

		#endregion

		#region Field Management

		private readonly List<DetailsViewField> _fieldDefinitions = new();

		/// <summary>
		/// Adds a field definition to the DetailsView.
		/// </summary>
		internal void AddField(DetailsViewField field)
		{
			_fieldDefinitions.Add(field);
			StateHasChanged();
		}

		/// <summary>
		/// Removes a field definition from the DetailsView.
		/// </summary>
		internal void RemoveField(DetailsViewField field)
		{
			_fieldDefinitions.Remove(field);
			StateHasChanged();
		}

		#endregion

		#region Computed Properties

		/// <summary>
		/// Determines whether the command row should be displayed.
		/// </summary>
		protected bool ShowCommandRow =>
			AutoGenerateEditButton || AutoGenerateDeleteButton || AutoGenerateInsertButton;

		/// <summary>
		/// Gets the gridlines attribute value for the table element.
		/// </summary>
		protected string GridLinesAttribute => GridLines switch
		{
			GridLines.Both => "all",
			GridLines.Horizontal => "rows",
			GridLines.Vertical => "cols",
			_ => "none"
		};

		/// <summary>
		/// Gets the border attribute value for the table element.
		/// </summary>
		protected string BorderAttribute => GridLines != GridLines.None ? "1" : "0";

		/// <summary>
		/// Gets the combined style string.
		/// </summary>
		protected string CombinedStyle
		{
			get
			{
				var styles = new List<string> { "border-collapse:collapse" };
				if (CellPadding >= 0)
				{
					styles.Add($"border-spacing:{CellSpacing}px");
				}
				return string.Join(";", styles);
			}
		}

		/// <summary>
		/// Gets the CSS style for the caption element based on CaptionAlign.
		/// </summary>
		protected string GetCaptionStyle()
		{
			return CaptionAlign switch
			{
				TableCaptionAlign.Top => "caption-side:top",
				TableCaptionAlign.Bottom => "caption-side:bottom",
				TableCaptionAlign.Left => "text-align:left",
				TableCaptionAlign.Right => "text-align:right",
				_ => null
			};
		}

		/// <summary>
		/// Gets the effective style for a data row based on mode and row index.
		/// Priority: EditRowStyle/InsertRowStyle > AlternatingRowStyle > RowStyle.
		/// </summary>
		protected TableItemStyle GetRowStyle(int rowIndex)
		{
			if (CurrentMode == DetailsViewMode.Edit && EditRowStyle != null)
				return EditRowStyle;
			if (CurrentMode == DetailsViewMode.Insert && InsertRowStyle != null)
				return InsertRowStyle;
			if (rowIndex % 2 == 1 && AlternatingRowStyle != null)
				return AlternatingRowStyle;
			return RowStyle;
		}

		#endregion

		#region Lifecycle

		protected override void OnInitialized()
		{
			base.OnInitialized();
			CurrentMode = DefaultMode;
		}

		protected override void OnParametersSet()
		{
			base.OnParametersSet();
			UpdateCurrentItem();
		}

		private void UpdateCurrentItem()
		{
			if (Items != null && Items.Any())
			{
				var itemsList = Items.ToList();
				if (PageIndex >= 0 && PageIndex < itemsList.Count)
				{
					CurrentItem = itemsList[PageIndex];
				}
				else if (itemsList.Count > 0)
				{
					PageIndex = 0;
					CurrentItem = itemsList[0];
				}
			}
			else
			{
				CurrentItem = default;
			}
		}

		#endregion

		#region Field Generation

		/// <summary>
		/// Gets the list of fields to display. Uses defined fields if available,
		/// otherwise auto-generates from the item type's properties.
		/// </summary>
		internal List<DetailsViewField> GetFields()
		{
			if (_fieldDefinitions.Any())
			{
				return _fieldDefinitions;
			}

			if (!AutoGenerateRows)
			{
				return new List<DetailsViewField>();
			}

			return GenerateAutoFields();
		}

		private List<DetailsViewField> GenerateAutoFields()
		{
			var fields = new List<DetailsViewField>();
			var properties = typeof(ItemType).GetProperties(BindingFlags.Public | BindingFlags.Instance);

			foreach (var prop in properties)
			{
				if (!prop.CanRead) continue;

				fields.Add(new DetailsViewAutoField(prop.Name, prop));
			}

			return fields;
		}

		#endregion

		#region Command Handling

		private async Task ChangeMode(DetailsViewMode newMode)
		{
			var args = new DetailsViewModeEventArgs(newMode, false);
			await ModeChanging.InvokeAsync(args);

			if (args.Cancel) return;

			CurrentMode = args.NewMode;
			await ModeChanged.InvokeAsync(args);
			StateHasChanged();
		}

		private async Task HandleCancel()
		{
			var args = new DetailsViewModeEventArgs(DefaultMode, true);
			await ModeChanging.InvokeAsync(args);

			if (args.Cancel) return;

			CurrentMode = args.NewMode;
			await ModeChanged.InvokeAsync(args);
			StateHasChanged();
		}

		private async Task HandleDelete()
		{
			var deleteArgs = new DetailsViewDeleteEventArgs(PageIndex);
			await ItemDeleting.InvokeAsync(deleteArgs);

			if (deleteArgs.Cancel) return;

			await ItemDeleted.InvokeAsync(new DetailsViewDeletedEventArgs(1, null));
			CurrentMode = DefaultMode;
			StateHasChanged();
		}

		private async Task HandleUpdate()
		{
			var updateArgs = new DetailsViewUpdateEventArgs("update");
			await ItemUpdating.InvokeAsync(updateArgs);

			if (updateArgs.Cancel) return;

			await ItemUpdated.InvokeAsync(new DetailsViewUpdatedEventArgs(1, null));

			var modeArgs = new DetailsViewModeEventArgs(DefaultMode, false);
			await ModeChanging.InvokeAsync(modeArgs);
			CurrentMode = DefaultMode;
			await ModeChanged.InvokeAsync(modeArgs);
			StateHasChanged();
		}

		private async Task HandleInsert()
		{
			var insertArgs = new DetailsViewInsertEventArgs("insert");
			await ItemInserting.InvokeAsync(insertArgs);

			if (insertArgs.Cancel) return;

			await ItemInserted.InvokeAsync(new DetailsViewInsertedEventArgs(1, null));

			var modeArgs = new DetailsViewModeEventArgs(DefaultMode, false);
			await ModeChanging.InvokeAsync(modeArgs);
			CurrentMode = DefaultMode;
			await ModeChanged.InvokeAsync(modeArgs);
			StateHasChanged();
		}

		private async Task GoToPage(int newPageIndex)
		{
			if (Items == null) return;

			var totalItems = Items.Count();
			var oldPageIndex = PageIndex;

			var args = new PageChangedEventArgs(newPageIndex, oldPageIndex, totalItems, newPageIndex);
			await PageIndexChanging.InvokeAsync(args);

			if (args.Cancel) return;

			PageIndex = args.NewPageIndex;
			UpdateCurrentItem();

			await PageIndexChanged.InvokeAsync(args);
			StateHasChanged();
		}

		#endregion
	}

	/// <summary>
	/// Represents a field in the DetailsView control.
	/// </summary>
	public abstract class DetailsViewField
	{
		/// <summary>
		/// Gets or sets the header text for this field.
		/// </summary>
		public string HeaderText { get; set; }

		/// <summary>
		/// Gets or sets whether this field is visible.
		/// </summary>
		public bool Visible { get; set; } = true;

		/// <summary>
		/// Gets the display value for the given data item and mode.
		/// </summary>
		public abstract RenderFragment GetValue(object dataItem, DetailsViewMode mode);
	}

	/// <summary>
	/// Represents an auto-generated field that reads a property value using reflection.
	/// </summary>
	internal class DetailsViewAutoField : DetailsViewField
	{
		private readonly PropertyInfo _property;

		public DetailsViewAutoField(string headerText, PropertyInfo property)
		{
			HeaderText = headerText;
			_property = property;
		}

		public override RenderFragment GetValue(object dataItem, DetailsViewMode mode)
		{
			var value = _property.GetValue(dataItem);
			var displayValue = value?.ToString() ?? string.Empty;

			return mode switch
			{
				DetailsViewMode.Edit => builder =>
				{
					builder.OpenElement(0, "input");
					builder.AddAttribute(1, "type", "text");
					builder.AddAttribute(2, "value", displayValue);
					builder.CloseElement();
				},
				DetailsViewMode.Insert => builder =>
				{
					builder.OpenElement(0, "input");
					builder.AddAttribute(1, "type", "text");
					builder.AddAttribute(2, "value", string.Empty);
					builder.CloseElement();
				},
				_ => builder => builder.AddContent(0, displayValue),
			};
		}
	}
}
