namespace BlazorWebFormsComponents
{
	/// <summary>
	/// Generated by T4 Template JavaScriptConstants.tt
	/// </summary>
	internal static class JavaScriptConstants
	{
		public const string setTitle = "bwfc.Page.setTitle";
		public const string getTitle = "bwfc.Page.getTitle";
	}
}
