using BlazorWebFormsComponents.Cli.Io;

namespace BlazorWebFormsComponents.Cli.Scaffolding;

/// <summary>
/// Generates GlobalUsings.cs with Blazor infrastructure and BWFC namespaces.
/// Ported from the GlobalUsings section of New-ProjectScaffold in bwfc-migrate.ps1.
/// </summary>
public class GlobalUsingsGenerator
{
    public string Generate(bool hasIdentity = false)
    {
        var content = @"// =============================================================================
// Global using directives for Web Forms → Blazor migration.
//
// Type aliases (Page, MasterPage, ImageClickEventArgs) are provided by the
// BlazorWebFormsComponents .targets file when consuming the NuGet package.
// This file adds the Blazor infrastructure and BWFC namespaces that emitted
// page code-behind files need even when the generated app references the local
// project directly during repo development.
//
// Generated by webforms-to-blazor — Layer 1 scaffold
// =============================================================================

// Blazor component infrastructure — provides [Inject], [Parameter],
// [SupplyParameterFromQuery], NavigationManager, ComponentBase, etc.
global using Microsoft.AspNetCore.Components;
global using Microsoft.AspNetCore.Components.Web;
global using Microsoft.AspNetCore.Components.Routing;

// BWFC namespaces used by generated page code-behind fields and validators.
global using BlazorWebFormsComponents;
global using BlazorWebFormsComponents.Enums;
global using BlazorWebFormsComponents.LoginControls;
global using BlazorWebFormsComponents.Validations;
";

        if (hasIdentity)
        {
            content += @"
// Identity infrastructure
global using Microsoft.AspNetCore.Components.Authorization;
global using Microsoft.AspNetCore.Identity;
";
        }

        return content;
    }

    public async Task WriteAsync(string outputRoot, OutputWriter writer, bool hasIdentity = false)
    {
        var content = Generate(hasIdentity);
        var path = Path.Combine(outputRoot, "GlobalUsings.cs");
        await writer.WriteFileAsync(path, content, "GlobalUsings.cs (Blazor infrastructure usings)");
    }
}
