using BlazorWebFormsComponents.Cli.Io;

namespace BlazorWebFormsComponents.Cli.Scaffolding;

/// <summary>
/// Generates shim files that bridge Web Forms types to BWFC equivalents.
/// WebFormsShims.cs provides using statements and initialization for BWFC's built-in shims.
/// IdentityShims.cs is only generated when HasIdentity is true.
/// </summary>
public class ShimGenerator
{
    public string GenerateWebFormsShims()
    {
        return @"// =============================================================================
// Web Forms compatibility shims for Blazor migration.
//
// These shims bridge common Web Forms types and patterns to their Blazor/BWFC
// equivalents. The BWFC NuGet package provides most type aliases automatically
// via its .targets file (Page, MasterPage, ImageClickEventArgs).
//
// This file adds project-level shims for patterns not covered by the package.
//
// DI registration: AddBlazorWebFormsComponents() in Program.cs registers:
//   - SessionShim     (scoped) — drop-in for Session[""key""] access
//   - CacheShim       (scoped) — drop-in for Cache[""key""] access
//   - ServerShim      (scoped) — drop-in for Server.MapPath() etc.
//   - ConfigurationManager — shim for AppSettings[""key""] access
//
// Code-behind files with Session[""key""] or Cache[""key""] get auto-wired
// [Inject] properties during L1 migration (SessionDetectTransform).
//
// Generated by webforms-to-blazor — Layer 1 scaffold
// =============================================================================

// ConfigurationManager shim — allows Web Forms configuration access patterns
// to work against ASP.NET Core's IConfiguration.
// Usage: ConfigurationManager.AppSettings[""key""] maps to IConfiguration[""key""]
using BlazorWebFormsComponents;
";
    }

    public string GenerateIdentityShims()
    {
        return @"// =============================================================================
// Identity compatibility shims for Blazor migration.
//
// These shims bridge ASP.NET Web Forms membership/identity patterns to
// ASP.NET Core Identity equivalents.
//
// Generated by webforms-to-blazor — Layer 1 scaffold
// =============================================================================

// TODO(bwfc-identity): Configure ASP.NET Core Identity to replace Web Forms Membership
// The following patterns need manual migration:
//   Membership.GetUser()          → UserManager<IdentityUser>.GetUserAsync()
//   Membership.ValidateUser()     → SignInManager<IdentityUser>.PasswordSignInAsync()
//   FormsAuthentication.SignOut()  → SignInManager<IdentityUser>.SignOutAsync()
//   Roles.IsUserInRole()          → UserManager<IdentityUser>.IsInRoleAsync()
//
// See: https://learn.microsoft.com/aspnet/core/security/authentication/identity

using Microsoft.AspNetCore.Identity;
";
    }

    public async Task WriteAsync(string outputRoot, OutputWriter writer, bool hasIdentity)
    {
        var shimPath = Path.Combine(outputRoot, "WebFormsShims.cs");
        await writer.WriteFileAsync(shimPath, GenerateWebFormsShims(), "WebFormsShims.cs");

        if (hasIdentity)
        {
            var identityPath = Path.Combine(outputRoot, "IdentityShims.cs");
            await writer.WriteFileAsync(identityPath, GenerateIdentityShims(), "IdentityShims.cs");
        }
    }
}
