using Microsoft.AspNetCore.Identity;

namespace WingtipToys.Models;

/// <summary>
/// Stub generated by BWFC migration CLI.
/// Add custom user properties as needed for your application.
/// </summary>
public class ApplicationUser : IdentityUser
{
}
