// TODO: Review — auto-copied and transformed DbContext from Web Forms source
// TODO: Verify EF Core configuration and connection string setup

using Microsoft.EntityFrameworkCore; // TODO: Verify EF Core using directive
namespace WingtipToys.Models
{
  public class ProductContext : DbContext
  {
    // TODO: EF Core constructor — auto-generated by migration script
    public ProductContext(DbContextOptions<ProductContext> options) : base(options) { }

    public DbSet<Category> Categories { get; set; }
    public DbSet<Product> Products { get; set; }
    public DbSet<CartItem> ShoppingCartItems { get; set; }
    public DbSet<Order> Orders { get; set; }
    public DbSet<OrderDetail> OrderDetails { get; set; }
  }
}
