<#
.SYNOPSIS
    Generates a Markdown performance report and SVG charts from benchmark JSON results.

.DESCRIPTION
    Reads the JSON output produced by Run-Benchmarks.ps1 and generates:
      1. A Markdown report with executive summary, methodology, result tables,
         and comparison analysis.
      2. SVG bar-chart images comparing .NET Framework vs .NET 10 response times.

.PARAMETER InputPath
    Path to the benchmark-results.json file.

.PARAMETER OutputPath
    Directory where the report and charts will be written.
    Default: dev-docs/benchmarks/

.EXAMPLE
    .\Generate-BenchmarkReport.ps1 -InputPath dev-docs\benchmarks\benchmark-results.json
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory)]
    [string]$InputPath,
    [string]$OutputPath
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path $PSScriptRoot -Parent
if (-not $OutputPath) {
    $OutputPath = Join-Path $repoRoot 'dev-docs\benchmarks'
}
if (-not (Test-Path $OutputPath)) {
    New-Item -ItemType Directory -Path $OutputPath -Force | Out-Null
}

# ── Load data ────────────────────────────────────────────────
if (-not (Test-Path $InputPath)) {
    Write-Error "Input file not found: $InputPath"
    exit 1
}

$data = Get-Content $InputPath -Raw | ConvertFrom-Json

# ── Helper: safe value formatting ────────────────────────────
function Fmt {
    param($Value, [string]$Suffix = '')
    if ($null -eq $Value) { return 'N/A' }
    return "$Value$Suffix"
}

# ══════════════════════════════════════════════════════════════
# MARKDOWN REPORT
# ══════════════════════════════════════════════════════════════

$pairs = @(
    @{ Label = 'WingtipToys'; Framework = 'WingtipToys'; Blazor = 'AfterWingtipToys' },
    @{ Label = 'ContosoUniversity'; Framework = 'ContosoUniversity'; Blazor = 'AfterContosoUniversity' }
)

$md = [System.Text.StringBuilder]::new()
$null = $md.AppendLine('# Performance Benchmark Report')
$null = $md.AppendLine('')
$null = $md.AppendLine('> Auto-generated by `scripts/Generate-BenchmarkReport.ps1`')
$null = $md.AppendLine('')

# Executive summary
$null = $md.AppendLine('## Executive Summary')
$null = $md.AppendLine('')
$null = $md.AppendLine('This report compares HTTP response-time performance between the original')
$null = $md.AppendLine('.NET Framework Web Forms sample applications and their .NET 10 Blazor')
$null = $md.AppendLine('equivalents in the BlazorWebFormsComponents project.')
$null = $md.AppendLine('')

$ts = if ($data.Environment.Timestamp) { $data.Environment.Timestamp } else { 'Unknown' }
$null = $md.AppendLine("**Run date:** $ts  ")
$null = $md.AppendLine("**Duration:** $(Fmt $data.DurationSeconds 's')  ")
$null = $md.AppendLine("**Iterations per page:** $(Fmt $data.Configuration.Iterations)")
$null = $md.AppendLine('')

# Methodology
$null = $md.AppendLine('## Methodology')
$null = $md.AppendLine('')
$null = $md.AppendLine('1. Each application is launched fresh before measurement.')
$null = $md.AppendLine('2. **Cold start**: The first HTTP request after launch (includes JIT, initialization).')
$null = $md.AppendLine('3. **Warm average**: Mean response time over N sequential requests (default 50).')
$null = $md.AppendLine('4. **P95**: 95th percentile response time from warm requests.')
$null = $md.AppendLine('5. .NET Framework apps run under IIS Express; Blazor apps use `dotnet run`.')
$null = $md.AppendLine('6. All requests use `Invoke-WebRequest -UseBasicParsing` (no JS execution).')
$null = $md.AppendLine('')
$null = $md.AppendLine('> **Note:** Results are machine-dependent. Focus on _relative_ comparisons,')
$null = $md.AppendLine('> not absolute numbers.')
$null = $md.AppendLine('')

# Environment
$null = $md.AppendLine('## Environment')
$null = $md.AppendLine('')
$null = $md.AppendLine("| Property | Value |")
$null = $md.AppendLine("| --- | --- |")
$env2 = $data.Environment
$null = $md.AppendLine("| OS | $(Fmt $env2.OS) |")
$null = $md.AppendLine("| Machine | $(Fmt $env2.MachineName) |")
$null = $md.AppendLine("| Processors | $(Fmt $env2.ProcessorCount) |")
$null = $md.AppendLine("| .NET SDK | $(Fmt $env2.DotNetVersion) |")
$null = $md.AppendLine("| PowerShell | $(Fmt $env2.PowerShell) |")
$null = $md.AppendLine('')

# Results per pair
foreach ($pair in $pairs) {
    $null = $md.AppendLine("## $($pair.Label)")
    $null = $md.AppendLine('')

    $fwResult = $data.Results.($pair.Framework)
    $blResult = $data.Results.($pair.Blazor)

    $fwSkipped = (-not $fwResult) -or ($fwResult.Skipped -eq $true)
    $blSkipped = (-not $blResult) -or ($blResult.Skipped -eq $true)

    if ($fwSkipped) {
        $reason = if ($fwResult -and $fwResult.Reason) { $fwResult.Reason } else { 'Not available' }
        $null = $md.AppendLine("> ⚠️ .NET Framework results unavailable: $reason")
        $null = $md.AppendLine('')
    }

    # Build table
    $null = $md.AppendLine("| Page | Platform | Cold (ms) | Avg (ms) | P95 (ms) | Min (ms) | Max (ms) | Size (B) | Status |")
    $null = $md.AppendLine("| --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |")

    # Collect page names from Blazor (always expected)
    $pageNames = @()
    if (-not $blSkipped) {
        $pageNames = $blResult.Pages | ForEach-Object { $_.Page }
    } elseif (-not $fwSkipped) {
        $pageNames = $fwResult.Pages | ForEach-Object { $_.Page }
    }

    foreach ($pageName in $pageNames) {
        # Framework row
        if (-not $fwSkipped) {
            $fp = $fwResult.Pages | Where-Object { $_.Page -eq $pageName } | Select-Object -First 1
            if ($fp -and -not $fp.Error) {
                $null = $md.AppendLine("| $pageName | .NET Framework | $(Fmt $fp.ColdStartMs) | $(Fmt $fp.AverageMs) | $(Fmt $fp.P95Ms) | $(Fmt $fp.MinMs) | $(Fmt $fp.MaxMs) | $(Fmt $fp.ResponseBytes) | $(Fmt $fp.StatusCode) |")
            } else {
                $err = if ($fp) { $fp.Error } else { 'No data' }
                $null = $md.AppendLine("| $pageName | .NET Framework | — | — | — | — | — | — | Error: $err |")
            }
        } else {
            $null = $md.AppendLine("| $pageName | .NET Framework | N/A | N/A | N/A | N/A | N/A | N/A | Skipped |")
        }

        # Blazor row
        if (-not $blSkipped) {
            $bp = $blResult.Pages | Where-Object { $_.Page -eq $pageName } | Select-Object -First 1
            if ($bp -and -not $bp.Error) {
                $null = $md.AppendLine("| $pageName | .NET 10 Blazor | $(Fmt $bp.ColdStartMs) | $(Fmt $bp.AverageMs) | $(Fmt $bp.P95Ms) | $(Fmt $bp.MinMs) | $(Fmt $bp.MaxMs) | $(Fmt $bp.ResponseBytes) | $(Fmt $bp.StatusCode) |")
            } else {
                $err = if ($bp) { $bp.Error } else { 'No data' }
                $null = $md.AppendLine("| $pageName | .NET 10 Blazor | — | — | — | — | — | — | Error: $err |")
            }
        } else {
            $null = $md.AppendLine("| $pageName | .NET 10 Blazor | N/A | N/A | N/A | N/A | N/A | N/A | Skipped |")
        }
    }
    $null = $md.AppendLine('')

    # Comparison / speedup table
    if (-not $fwSkipped -and -not $blSkipped) {
        $null = $md.AppendLine("### Speedup Analysis")
        $null = $md.AppendLine('')
        $null = $md.AppendLine("| Page | Framework Avg (ms) | Blazor Avg (ms) | Speedup | Cold Start Δ |")
        $null = $md.AppendLine("| --- | ---: | ---: | ---: | --- |")

        foreach ($pageName in $pageNames) {
            $fp = $fwResult.Pages | Where-Object { $_.Page -eq $pageName } | Select-Object -First 1
            $bp = $blResult.Pages | Where-Object { $_.Page -eq $pageName } | Select-Object -First 1

            $fAvg = if ($fp -and $fp.AverageMs) { $fp.AverageMs } else { $null }
            $bAvg = if ($bp -and $bp.AverageMs) { $bp.AverageMs } else { $null }

            $speedup = 'N/A'
            if ($fAvg -and $bAvg -and $bAvg -gt 0) {
                $ratio = [math]::Round($fAvg / $bAvg, 2)
                $speedup = if ($ratio -gt 1) { "${ratio}x faster (Blazor)" } elseif ($ratio -lt 1) { "$([math]::Round(1/$ratio, 2))x faster (Framework)" } else { 'Equal' }
            }

            $coldDelta = 'N/A'
            $fCold = if ($fp -and $fp.ColdStartMs) { $fp.ColdStartMs } else { $null }
            $bCold = if ($bp -and $bp.ColdStartMs) { $bp.ColdStartMs } else { $null }
            if ($null -ne $fCold -and $null -ne $bCold) {
                $diff = $bCold - $fCold
                $coldDelta = if ($diff -gt 0) { "+${diff}ms (Blazor slower)" } elseif ($diff -lt 0) { "$([math]::Abs($diff))ms faster (Blazor)" } else { 'Equal' }
            }

            $null = $md.AppendLine("| $pageName | $(Fmt $fAvg) | $(Fmt $bAvg) | $speedup | $coldDelta |")
        }
        $null = $md.AppendLine('')
    }
}

# Chart references
$null = $md.AppendLine('## Charts')
$null = $md.AppendLine('')
$null = $md.AppendLine('![WingtipToys Response Times](response-times-wingtiptoys.svg)')
$null = $md.AppendLine('')
$null = $md.AppendLine('![ContosoUniversity Response Times](response-times-contosouniversity.svg)')
$null = $md.AppendLine('')

# Known limitations
$null = $md.AppendLine('## Known Limitations')
$null = $md.AppendLine('')
$null = $md.AppendLine('- Benchmarks measure server-side HTTP response time only (no browser rendering).')
$null = $md.AppendLine('- Blazor apps serve interactive pages; the initial HTML payload is a shell that')
$null = $md.AppendLine('  loads SignalR. Direct size comparisons may not reflect perceived performance.')
$null = $md.AppendLine('- .NET Framework apps require IIS Express and may not run on all machines.')
$null = $md.AppendLine('- Results vary by machine — focus on relative differences.')
$null = $md.AppendLine('- No concurrent-load testing (single sequential client).')
$null = $md.AppendLine('')

$reportFile = Join-Path $OutputPath 'performance-report.md'
$md.ToString() | Set-Content -Path $reportFile -Encoding UTF8
Write-Host "  Report written to $reportFile" -ForegroundColor Green

# ══════════════════════════════════════════════════════════════
# SVG CHART GENERATION
# ══════════════════════════════════════════════════════════════

function New-BarChartSvg {
    param(
        [string]$Title,
        [array]$PageNames,
        [array]$FrameworkValues,
        [array]$BlazorValues,
        [bool]$FrameworkAvailable = $true
    )

    $chartW      = 600
    $chartH      = 350
    $marginTop   = 60
    $marginBot   = 80
    $marginLeft  = 70
    $marginRight = 30
    $plotW       = $chartW - $marginLeft - $marginRight
    $plotH       = $chartH - $marginTop - $marginBot

    # Determine max value for scale
    $allVals = @()
    if ($FrameworkAvailable) { $allVals += $FrameworkValues | Where-Object { $null -ne $_ } }
    $allVals += $BlazorValues | Where-Object { $null -ne $_ }
    $maxVal = if ($allVals.Count -gt 0) { ($allVals | Measure-Object -Maximum).Maximum } else { 100 }
    if ($maxVal -le 0) { $maxVal = 100 }
    $maxVal = [math]::Ceiling($maxVal * 1.15)  # 15% headroom

    $groupCount = $PageNames.Count
    $groupW     = [math]::Floor($plotW / $groupCount)
    $barW       = [math]::Floor($groupW * 0.30)
    $gap        = [math]::Floor($groupW * 0.10)

    $svg = [System.Text.StringBuilder]::new()
    $null = $svg.AppendLine("<?xml version=`"1.0`" encoding=`"UTF-8`"?>")
    $null = $svg.AppendLine("<svg xmlns=`"http://www.w3.org/2000/svg`" viewBox=`"0 0 $chartW $chartH`" font-family=`"system-ui, sans-serif`">")

    # Background
    $null = $svg.AppendLine("  <rect width=`"$chartW`" height=`"$chartH`" fill=`"#fafafa`" rx=`"8`"/>")

    # Title
    $null = $svg.AppendLine("  <text x=`"$([math]::Floor($chartW/2))`" y=`"30`" text-anchor=`"middle`" font-size=`"16`" font-weight=`"bold`" fill=`"#333`">$Title</text>")

    # Y-axis gridlines (5 ticks)
    for ($i = 0; $i -le 4; $i++) {
        $val = [math]::Round($maxVal * $i / 4, 0)
        $y   = $marginTop + $plotH - [math]::Floor($plotH * $i / 4)
        $null = $svg.AppendLine("  <line x1=`"$marginLeft`" y1=`"$y`" x2=`"$($marginLeft + $plotW)`" y2=`"$y`" stroke=`"#ddd`" stroke-width=`"1`"/>")
        $null = $svg.AppendLine("  <text x=`"$($marginLeft - 8)`" y=`"$($y + 4)`" text-anchor=`"end`" font-size=`"11`" fill=`"#666`">$val</text>")
    }

    # Y-axis label
    $null = $svg.AppendLine("  <text x=`"15`" y=`"$([math]::Floor($marginTop + $plotH/2))`" text-anchor=`"middle`" font-size=`"12`" fill=`"#666`" transform=`"rotate(-90, 15, $([math]::Floor($marginTop + $plotH/2)))`">Avg Response Time (ms)</text>")

    # Bars
    for ($g = 0; $g -lt $groupCount; $g++) {
        $groupX = $marginLeft + ($g * $groupW) + $gap

        # Framework bar
        if ($FrameworkAvailable -and $null -ne $FrameworkValues[$g]) {
            $barH = [math]::Max(1, [math]::Floor($plotH * $FrameworkValues[$g] / $maxVal))
            $barY = $marginTop + $plotH - $barH
            $null = $svg.AppendLine("  <rect x=`"$groupX`" y=`"$barY`" width=`"$barW`" height=`"$barH`" fill=`"#4472C4`" rx=`"2`"/>")
            $null = $svg.AppendLine("  <text x=`"$($groupX + [math]::Floor($barW/2))`" y=`"$($barY - 4)`" text-anchor=`"middle`" font-size=`"10`" fill=`"#4472C4`">$($FrameworkValues[$g])</text>")
        }

        # Blazor bar
        $blazorX = $groupX + $barW + [math]::Floor($gap / 2)
        if ($null -ne $BlazorValues[$g]) {
            $barH = [math]::Max(1, [math]::Floor($plotH * $BlazorValues[$g] / $maxVal))
            $barY = $marginTop + $plotH - $barH
            $null = $svg.AppendLine("  <rect x=`"$blazorX`" y=`"$barY`" width=`"$barW`" height=`"$barH`" fill=`"#ED7D31`" rx=`"2`"/>")
            $null = $svg.AppendLine("  <text x=`"$($blazorX + [math]::Floor($barW/2))`" y=`"$($barY - 4)`" text-anchor=`"middle`" font-size=`"10`" fill=`"#ED7D31`">$($BlazorValues[$g])</text>")
        }

        # X-axis label
        $labelX = $groupX + [math]::Floor(($barW * 2 + $gap) / 2)
        $labelY = $marginTop + $plotH + 18
        $null = $svg.AppendLine("  <text x=`"$labelX`" y=`"$labelY`" text-anchor=`"middle`" font-size=`"12`" fill=`"#333`">$($PageNames[$g])</text>")
    }

    # Legend
    $legendY = $chartH - 20
    $null = $svg.AppendLine("  <rect x=`"$([math]::Floor($chartW/2) - 120)`" y=`"$($legendY - 10)`" width=`"14`" height=`"14`" fill=`"#4472C4`" rx=`"2`"/>")
    $null = $svg.AppendLine("  <text x=`"$([math]::Floor($chartW/2) - 102)`" y=`"$legendY`" font-size=`"11`" fill=`"#333`">.NET Framework</text>")
    $null = $svg.AppendLine("  <rect x=`"$([math]::Floor($chartW/2) + 10)`" y=`"$($legendY - 10)`" width=`"14`" height=`"14`" fill=`"#ED7D31`" rx=`"2`"/>")
    $null = $svg.AppendLine("  <text x=`"$([math]::Floor($chartW/2) + 28)`" y=`"$legendY`" font-size=`"11`" fill=`"#333`">.NET 10 Blazor</text>")

    $null = $svg.AppendLine("</svg>")
    return $svg.ToString()
}

foreach ($pair in $pairs) {
    $fwResult = $data.Results.($pair.Framework)
    $blResult = $data.Results.($pair.Blazor)

    $fwSkipped = (-not $fwResult) -or ($fwResult.Skipped -eq $true)
    $blSkipped = (-not $blResult) -or ($blResult.Skipped -eq $true)

    # Determine page names from whichever is available
    $pageNames = @()
    $fwAvgVals = @()
    $blAvgVals = @()

    if (-not $blSkipped -and -not $fwSkipped) {
        # Both available — union page names from both
        $pageNames = @($blResult.Pages | ForEach-Object { $_.Page })
    } elseif (-not $blSkipped) {
        $pageNames = @($blResult.Pages | ForEach-Object { $_.Page })
    } elseif (-not $fwSkipped) {
        $pageNames = @($fwResult.Pages | ForEach-Object { $_.Page })
    }

    # Build value arrays aligned to $pageNames
    if (-not $fwSkipped) {
        $fwAvgVals = @(foreach ($pn in $pageNames) {
            $pg = $fwResult.Pages | Where-Object { $_.Page -eq $pn } | Select-Object -First 1
            if ($pg -and -not $pg.Error) { $pg.AverageMs } else { $null }
        })
    } else {
        $fwAvgVals = @($pageNames | ForEach-Object { $null })
    }

    if (-not $blSkipped) {
        $blAvgVals = @(foreach ($pn in $pageNames) {
            $pg = $blResult.Pages | Where-Object { $_.Page -eq $pn } | Select-Object -First 1
            if ($pg -and -not $pg.Error) { $pg.AverageMs } else { $null }
        })
    } else {
        $blAvgVals = @($pageNames | ForEach-Object { $null })
    }

    if ($pageNames.Count -eq 0) {
        Write-Host "  Skipping chart for $($pair.Label) — no page data" -ForegroundColor Yellow
        continue
    }

    $svgContent = New-BarChartSvg `
        -Title "$($pair.Label) — Avg Response Time (ms)" `
        -PageNames $pageNames `
        -FrameworkValues $fwAvgVals `
        -BlazorValues $blAvgVals `
        -FrameworkAvailable (-not $fwSkipped)

    $chartFile = Join-Path $OutputPath "response-times-$($pair.Label.ToLower()).svg"
    $svgContent | Set-Content -Path $chartFile -Encoding UTF8
    Write-Host "  Chart written to $chartFile" -ForegroundColor Green
}

Write-Host ''
Write-Host '  Report generation complete.' -ForegroundColor Green
