using Microsoft.Playwright;

namespace AfterBlazorServerSide.Tests;

[Collection(nameof(PlaywrightCollection))]
public class ControlSampleTests
{
    private readonly PlaywrightFixture _fixture;

    public ControlSampleTests(PlaywrightFixture fixture)
    {
        _fixture = fixture;
    }

    // Editor Controls
    [Theory]
    [InlineData("/ControlSamples/Button")]
    [InlineData("/ControlSamples/CheckBox")]
    [InlineData("/ControlSamples/CheckBox/Events")]
    [InlineData("/ControlSamples/CheckBox/Style")]
    [InlineData("/ControlSamples/HyperLink")]
    [InlineData("/ControlSamples/LinkButton")]
    [InlineData("/ControlSamples/Literal")]
    [InlineData("/ControlSamples/DropDownList")]
    [InlineData("/ControlSamples/Panel")]
    [InlineData("/ControlSamples/PlaceHolder")]
    [InlineData("/ControlSamples/RadioButton")]
    [InlineData("/ControlSamples/RadioButtonList")]
    [InlineData("/ControlSamples/TextBox")]
    public async Task EditorControl_Loads_WithoutErrors(string path)
    {
        await VerifyPageLoadsWithoutErrors(path);
    }

    // Data Controls
    [Theory]
    [InlineData("/ControlSamples/DataGrid")]
    [InlineData("/ControlSamples/DataGrid/AutoGeneratedColumns")]
    [InlineData("/ControlSamples/DataGrid/ShowHideHeader")]
    [InlineData("/ControlSamples/DataList")]
    [InlineData("/ControlSamples/Repeater")]
    [InlineData("/ControlSamples/ListView")]
    [InlineData("/ControlSamples/ListView/ItemDataBound")]
    [InlineData("/ControlSamples/GridView")]
    [InlineData("/ControlSamples/GridView/AutoGeneratedColumns")]
    [InlineData("/ControlSamples/GridView/BindAttribute")]
    [InlineData("/ControlSamples/GridView/TemplateFields")]
    [InlineData("/ControlSamples/FormView/Simple")]
    [InlineData("/ControlSamples/FormView/Edit")]
    public async Task DataControl_Loads_WithoutErrors(string path)
    {
        await VerifyPageLoadsWithoutErrors(path);
    }

    /// <summary>
    /// Tests the ListView ItemDataBound event functionality by verifying that
    /// the sample page loads and displays the expected content.
    /// </summary>
    [Fact]
    public async Task ListView_ItemDataBound_DisplaysItemProperties()
    {
        // Arrange
        var page = await _fixture.NewPageAsync();

        try
        {
            // Act - Use DOMContentLoaded instead of NetworkIdle to avoid Blazor SignalR connection delays
            var response = await page.GotoAsync($"{_fixture.BaseUrl}/ControlSamples/ListView/ItemDataBound", new PageGotoOptions
            {
                WaitUntil = WaitUntilState.DOMContentLoaded,
                Timeout = 30000
            });

            // Wait for the component to render
            await page.WaitForSelectorAsync(".item-row", new PageWaitForSelectorOptions { Timeout = 5000 });

            // Assert - Page loads successfully
            Assert.NotNull(response);
            Assert.True(response.Ok, $"Page failed to load with status: {response.Status}");

            // Assert - Table rows are rendered
            var itemRows = await page.Locator(".item-row, .alt-item-row").AllAsync();
            Assert.NotEmpty(itemRows);

            // Assert - Event counter shows item count
            var eventCount = await page.Locator("#event-count").TextContentAsync();
            Assert.NotNull(eventCount);
            Assert.Contains("12", eventCount); // SimpleWidgetList has 12 items

            // Assert - Event details section exists
            var eventDetails = await page.Locator("#event-details").IsVisibleAsync();
            Assert.True(eventDetails);
        }
        finally
        {
            await page.CloseAsync();
        }
    }

    // Navigation Controls
    [Theory]
    [InlineData("/ControlSamples/TreeView")]
    public async Task NavigationControl_Loads_WithoutErrors(string path)
    {
        await VerifyPageLoadsWithoutErrors(path);
    }

    // Menu component tests - Menu has known JS interop requirements that may produce console errors
    // Testing separately to verify the page loads and renders content
    [Theory]
    [InlineData("/ControlSamples/Menu")]
    [InlineData("/ControlSamples/Menu/DatabindingSitemap")]
    public async Task MenuControl_Loads_AndRendersContent(string path)
    {
        await VerifyMenuPageLoads(path);
    }

    // Validation Controls
    [Theory]
    [InlineData("/ControlSamples/RequiredFieldValidator")]
    [InlineData("/ControlSamples/RangeValidator")]
    [InlineData("/ControlSamples/CompareValidator")]
    [InlineData("/ControlSamples/CustomValidator")]
    [InlineData("/ControlSamples/RegularExpressionValidator")]
    [InlineData("/ControlSamples/ValidationSummary")]
    public async Task ValidationControl_Loads_WithoutErrors(string path)
    {
        await VerifyPageLoadsWithoutErrors(path);
    }

    // Login Controls
    [Theory]
    [InlineData("/ControlSamples/Login")]
    [InlineData("/ControlSamples/LoginName")]
    [InlineData("/ControlSamples/LoginStatusAuthenticated")]
    [InlineData("/ControlSamples/LoginStatusNotAuthenticated")]
    public async Task LoginControl_Loads_WithoutErrors(string path)
    {
        await VerifyPageLoadsWithoutErrors(path);
    }

    // Other Controls
    [Theory]
    [InlineData("/ControlSamples/AdRotator")]
    public async Task OtherControl_Loads_WithoutErrors(string path)
    {
        await VerifyPageLoadsWithoutErrors(path);
    }

    /// <summary>
    /// Validates that AdRotator displays an ad with the correct attributes.
    /// This specifically tests that Ads.xml is properly deployed and accessible.
    /// </summary>
    [Fact]
    public async Task AdRotator_DisplaysAd_WithCorrectAttributes()
    {
        // Arrange
        var page = await _fixture.NewPageAsync();

        try
        {
            // Act
            var response = await page.GotoAsync($"{_fixture.BaseUrl}/ControlSamples/AdRotator", new PageGotoOptions
            {
                WaitUntil = WaitUntilState.NetworkIdle,
                Timeout = 30000
            });

            // Assert - Page loads successfully
            Assert.NotNull(response);
            Assert.True(response.Ok, $"Page failed to load with status: {response.Status}");

            // Assert - AdRotator component rendered (look for images from Ads.xml)
            // The AdRotator renders as: <a href="..."><img src="/img/CSharp.png" OR "/img/VB.png" alt="..." /></a>
            // Look for the specific image sources that come from Ads.xml
            var adImage = await page.QuerySelectorAsync("img[src='/img/CSharp.png'], img[src='/img/VB.png']");
            Assert.NotNull(adImage);
            Assert.True(await adImage.IsVisibleAsync(), "Ad image should be visible");
            
            // Verify alt text is one of the expected values from Ads.xml
            var altText = await adImage.GetAttributeAsync("alt");
            Assert.NotNull(altText);
            Assert.NotEmpty(altText);
            Assert.Contains(altText, new[] { "CSharp", "Visual Basic" });
        }
        finally
        {
            await page.CloseAsync();
        }
    }

    private async Task VerifyPageLoadsWithoutErrors(string path)
    {
        // Arrange
        var page = await _fixture.NewPageAsync();
        var consoleErrors = new List<string>();
        var pageErrors = new List<string>();

        page.Console += (_, msg) =>
        {
            if (msg.Type == "error")
            {
                consoleErrors.Add($"{path}: {msg.Text}");
            }
        };

        page.PageError += (_, error) =>
        {
            pageErrors.Add($"{path}: {error}");
        };

        try
        {
            // Act
            var response = await page.GotoAsync($"{_fixture.BaseUrl}{path}", new PageGotoOptions
            {
                WaitUntil = WaitUntilState.NetworkIdle,
                Timeout = 30000
            });

            // Assert
            Assert.NotNull(response);
            Assert.True(response.Ok, $"Page {path} failed to load with status: {response.Status}");
            Assert.Empty(consoleErrors);
            Assert.Empty(pageErrors);
        }
        finally
        {
            await page.CloseAsync();
        }
    }

    /// <summary>
    /// Verifies Menu pages load and render content. Menu component has known JS interop 
    /// requirements (bwfc.Page.AddScriptElement) that may produce console errors when
    /// the JavaScript setup is not configured, but the page should still render.
    /// </summary>
    private async Task VerifyMenuPageLoads(string path)
    {
        // Arrange
        var page = await _fixture.NewPageAsync();
        var pageErrors = new List<string>();

        page.PageError += (_, error) =>
        {
            pageErrors.Add($"{path}: {error}");
        };

        try
        {
            // Act
            var response = await page.GotoAsync($"{_fixture.BaseUrl}{path}", new PageGotoOptions
            {
                WaitUntil = WaitUntilState.NetworkIdle,
                Timeout = 30000
            });

            // Assert - Page loads successfully
            Assert.NotNull(response);
            Assert.True(response.Ok, $"Page {path} failed to load with status: {response.Status}");
            
            // Assert - Page renders menu content (tables, links, or list items)
            var menuContent = await page.Locator("table, a, li, td").AllAsync();
            Assert.NotEmpty(menuContent);
            
            // Note: We don't check console errors for Menu pages because the Menu component
            // requires JavaScript setup (bwfc.Page.AddScriptElement) that may not be configured
            // in all environments. The important thing is that the page renders.
            
            Assert.Empty(pageErrors);
        }
        finally
        {
            await page.CloseAsync();
        }
    }
}
