using Microsoft.Playwright;

namespace AfterBlazorServerSide.Tests;

[Collection(nameof(PlaywrightCollection))]
public class ControlSampleTests
{
    private readonly PlaywrightFixture _fixture;

    public ControlSampleTests(PlaywrightFixture fixture)
    {
        _fixture = fixture;
    }

    // Editor Controls
    [Theory]
    [InlineData("/ControlSamples/Button")]
    [InlineData("/ControlSamples/CheckBox")]
    [InlineData("/ControlSamples/HyperLink")]
    [InlineData("/ControlSamples/LinkButton")]
    [InlineData("/ControlSamples/Literal")]
    [InlineData("/ControlSamples/DropDownList")]
    public async Task EditorControl_Loads_WithoutErrors(string path)
    {
        await VerifyPageLoadsWithoutErrors(path);
    }

    // Data Controls
    [Theory]
    [InlineData("/ControlSamples/DataList")]
    [InlineData("/ControlSamples/Repeater")]
    [InlineData("/ControlSamples/ListView")]
    [InlineData("/ControlSamples/GridView")]
    [InlineData("/ControlSamples/GridView/AutoGeneratedColumns")]
    [InlineData("/ControlSamples/GridView/BindAttribute")]
    [InlineData("/ControlSamples/GridView/TemplateFields")]
    [InlineData("/ControlSamples/FormView/Simple")]
    [InlineData("/ControlSamples/FormView/Edit")]
    public async Task DataControl_Loads_WithoutErrors(string path)
    {
        await VerifyPageLoadsWithoutErrors(path);
    }

    // Navigation Controls
    [Theory]
    [InlineData("/ControlSamples/TreeView")]
    public async Task NavigationControl_Loads_WithoutErrors(string path)
    {
        await VerifyPageLoadsWithoutErrors(path);
    }

    // Validation Controls
    [Theory]
    [InlineData("/ControlSamples/RequiredFieldValidator")]
    [InlineData("/ControlSamples/RangeValidator")]
    [InlineData("/ControlSamples/CompareValidator")]
    [InlineData("/ControlSamples/CustomValidator")]
    [InlineData("/ControlSamples/RegularExpressionValidator")]
    [InlineData("/ControlSamples/ValidationSummary")]
    public async Task ValidationControl_Loads_WithoutErrors(string path)
    {
        await VerifyPageLoadsWithoutErrors(path);
    }

    // Login Controls
    [Theory]
    [InlineData("/ControlSamples/Login")]
    [InlineData("/ControlSamples/LoginName")]
    [InlineData("/ControlSamples/LoginStatusAuthenticated")]
    [InlineData("/ControlSamples/LoginStatusNotAuthenticated")]
    public async Task LoginControl_Loads_WithoutErrors(string path)
    {
        await VerifyPageLoadsWithoutErrors(path);
    }

    // Other Controls
    [Theory]
    [InlineData("/ControlSamples/AdRotator")]
    public async Task OtherControl_Loads_WithoutErrors(string path)
    {
        await VerifyPageLoadsWithoutErrors(path);
    }

    /// <summary>
    /// Validates that AdRotator displays an ad with the correct attributes.
    /// This specifically tests that Ads.xml is properly deployed and accessible.
    /// </summary>
    [Fact]
    public async Task AdRotator_DisplaysAd_WithCorrectAttributes()
    {
        // Arrange
        var page = await _fixture.NewPageAsync();

        try
        {
            // Act
            var response = await page.GotoAsync($"{_fixture.BaseUrl}/ControlSamples/AdRotator", new PageGotoOptions
            {
                WaitUntil = WaitUntilState.NetworkIdle,
                Timeout = 30000
            });

            // Assert - Page loads successfully
            Assert.NotNull(response);
            Assert.True(response.Ok, $"Page failed to load with status: {response.Status}");

            // Assert - AdRotator component rendered with an ad image
            var adImage = await page.QuerySelectorAsync("img[alt]");
            Assert.NotNull(adImage);
            Assert.True(await adImage.IsVisibleAsync(), "Ad image should be visible");

            // Assert - Ad has valid alt text (proving Ads.xml was loaded)
            var altText = await adImage.GetAttributeAsync("alt");
            Assert.NotNull(altText);
            Assert.NotEmpty(altText);

            // Assert - Ad image is wrapped in an anchor tag with href (check parent element)
            var href = await adImage.EvaluateAsync<string>("el => el.parentElement?.tagName === 'A' ? el.parentElement.getAttribute('href') : null");
            Assert.NotNull(href);
            Assert.NotEmpty(href);
        }
        finally
        {
            await page.CloseAsync();
        }
    }

    private async Task VerifyPageLoadsWithoutErrors(string path)
    {
        // Arrange
        var page = await _fixture.NewPageAsync();
        var consoleErrors = new List<string>();
        var pageErrors = new List<string>();

        page.Console += (_, msg) =>
        {
            if (msg.Type == "error")
            {
                consoleErrors.Add($"{path}: {msg.Text}");
            }
        };

        page.PageError += (_, error) =>
        {
            pageErrors.Add($"{path}: {error}");
        };

        try
        {
            // Act
            var response = await page.GotoAsync($"{_fixture.BaseUrl}{path}", new PageGotoOptions
            {
                WaitUntil = WaitUntilState.NetworkIdle,
                Timeout = 30000
            });

            // Assert
            Assert.NotNull(response);
            Assert.True(response.Ok, $"Page {path} failed to load with status: {response.Status}");
            Assert.Empty(consoleErrors);
            Assert.Empty(pageErrors);
        }
        finally
        {
            await page.CloseAsync();
        }
    }
}
